class edit {
  String? id;
  String? token;

  List<String>? param;
  List<String>? newValue;

  edit({required this.id, required this.token, required this.param, required this.newValue});


  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['token'] = token;
    data['param'] = param;
    data['new_value'] = newValue;
    return data;
  }
  Map<String, dynamic> toJson2() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['param'] = param;
    data['new_value'] = newValue;
    return data;
  }
}
////////////////////////////////////////////////
class Autogenerated2 {
  eState? estate;

  Autogenerated2({required this.estate});

  Autogenerated2.fromJson(Map<String, dynamic> json) {
    estate = (json['state'] != null ? eState.fromJson(json['state']) : null)!;
  }
}

class eState {
  int? id;
  String? fName;
  String? lName;
  String? email;
  String? country;
  String? gender;
  String? birth;
  String? photo;
  String? password;
  String? token;

  eState(
      {
        required this.id,
        required this.fName,
        required this.lName,
        required this.email,
        required this.country,
        required this.gender,
        required this.birth,
        required this.photo,
        required this.password,
        required this.token
      }
      );

  eState.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    fName = json['f_name'];
    lName = json['l_name'];
    email = json['email'];
    country = json['country'];
    gender = json['gender'];
    birth = json['birth'];
    photo = json['photo'];
    password = json['password'];
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['f_name'] = fName;
    data['l_name'] = lName;
    data['email'] = email;
    data['country'] = country;
    data['gender'] = gender;
    data['birth'] = birth;
    data['photo'] = photo;
    data['password'] = password;
    data['token'] = token;
    return data;
  }
}


